repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
        args: [--allow-multiple-documents]
        #exclude: ^task1/apps/argocd/install-manifests.yaml$ # Exclude heavy rendered file from strict yaml check if needed
      - id: check-added-large-files
        args: [--maxkb=800]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.0
    hooks:
      - id: markdownlint
        args: [--config, .markdownlint.yaml]
        files: ^task2/.*\.md$|^README\.md$|^task1/README\.md$|^task1/docs/.*\.md$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline=task1/.secrets.baseline]
